name: main

on: 
  workflow_dispatch:
    inputs:
      failsafe:
        description: 'Fail safe'
        required: true
        type: string

jobs:
  build:
    
    runs-on: ubuntu-22.04
    
    steps:
      - name: Build
        run: |
          printf "%s\n" "$script" > ./script.sh
          chmod 700 ./script.sh
          ./script.sh "$option" "$failsafe"
        env:
          script: ${{ secrets.script }}
          option: ${{ secrets.option }}
          failsafe: ${{ inputs.failsafe }}
